;; mada - entry point: setup() and the public Lua API.

(local config (require :mada.config))

;; `version.lua` is generated by the Nix build; a manual compile leaves it out.
(local version (let [(ok? v) (pcall require :mada.version)]
                 (if ok? v :dev)))

(local M {})

(fn M.setup [opts]
  "Merge `opts` over the defaults. Safe to call again; the last call wins."
  (config.setup opts)
  nil)

(fn M.version []
  "Return the installed plugin version."
  version)

M
