;; mada - entry point: setup() and the public Lua API (FR-A2).

(local config (require :mada.config))
(local state (require :mada.state))
(local events (require :mada.events))
(local hl (require :mada.hl))
(local query (require :mada.query))
(local mermaid (require :mada.mermaid))
(local log (require :mada.log))

;; `version.lua` is generated by the Nix build; a manual compile leaves it out.
(local version (let [(ok? v) (pcall require :mada.version)]
                 (if ok? v :dev)))

(local M {})
(var initialized false)

(fn resolve_buf [buf]
  (if (or (= buf nil) (= buf 0)) (vim.api.nvim_get_current_buf) buf))

(fn attach_loaded_buffers [cfg]
  (each [_ buf (ipairs (vim.api.nvim_list_bufs))]
    (when (and (vim.api.nvim_buf_is_loaded buf)
               (vim.tbl_contains cfg.filetypes (. vim.bo buf :filetype)))
      (events.attach buf))))

(fn M.setup [opts]
  "Merge `opts` over the defaults, validate, and (re)render every attached
buffer with the new config (FR-C1, FR-C2). Also attaches already-loaded
buffers of a configured filetype (covers lazy loading)."
  (set initialized true)
  (let [cfg (config.setup opts)]
    (hl.define)
    (query.setup cfg)
    (events.setup_global cfg)
    (each [buf st (pairs (state.all))]
      (set st.cfg (vim.deepcopy cfg))
      (events.reevaluate_highlighter buf st cfg)
      (when (not st.raw)
        (events.enter_rendered buf)))
    (attach_loaded_buffers cfg))
  nil)

(fn M.version []
  "Return the installed plugin version."
  version)

(fn M.enable [?buf]
  "Attach buf (or the current buffer), clearing a prior :Mada disable."
  (let [buf (resolve_buf ?buf)]
    (log.guard :Enable buf
               (fn []
                 (tset (. vim.b buf) :mada_disabled nil)
                 (events.attach buf true)))))

(fn M.disable [?buf]
  "Detach buf (or the current buffer): clear marks, restore options, stop a
highlighter mada started, detach autocommands (FR-M7)."
  (let [buf (resolve_buf ?buf)]
    (log.guard :Disable buf (fn []
                              (tset (. vim.b buf) :mada_disabled true)
                              (events.detach buf)))))

(fn M.toggle [?buf]
  "Enable if disabled, disable if enabled."
  (let [buf (resolve_buf ?buf)]
    (log.guard :Toggle buf (fn []
                             (if (M.is_enabled buf) (M.disable buf)
                                 (M.enable buf))))))

(fn M.render [?buf ?opts]
  "Re-render every window showing buf. `opts.force = true` re-runs every
diagram, including failed ones."
  (let [buf (resolve_buf ?buf)]
    (log.guard :Render buf
               (fn []
                 (let [st (state.get buf)]
                   (when st
                     (when (and ?opts ?opts.force)
                       (mermaid.reset buf))
                     (each [_ w (ipairs (vim.api.nvim_list_wins))]
                       (when (= (vim.api.nvim_win_get_buf w) buf)
                         (events.render_view buf w)))))))))

(fn M.clear [?buf]
  "Clear buf's marks without detaching."
  (let [buf (resolve_buf ?buf)]
    (log.guard :Clear buf (fn []
                            (vim.api.nvim_buf_clear_namespace buf (state.ns) 0
                                                              -1)
                            (let [st (state.get buf)]
                              (when st
                                (set st.clean {})))))))

(fn M.is_enabled [?buf]
  "Whether buf is currently attached."
  (let [buf (resolve_buf ?buf)]
    (not= (state.get buf) nil)))

(fn M.on_filetype [buf]
  "Entry point for plugin/mada.lua's bootstrap FileType autocommand. Runs
setup() with defaults first if the user never called it (FR-C6)."
  (when (not initialized)
    (M.setup {}))
  (events.attach buf))

(fn M.command [cmd]
  "Dispatch `:Mada {enable|disable|toggle|render|clear}` (FR-A1)."
  (let [buf (vim.api.nvim_get_current_buf)]
    (log.guard :Command buf
               (fn []
                 (let [sub (. cmd.fargs 1)]
                   (if (= sub :enable) (M.enable buf) (= sub :disable)
                       (M.disable buf) (= sub :toggle) (M.toggle buf)
                       (= sub :render) (M.render buf {:force cmd.bang})
                       (= sub :clear) (M.clear buf)
                       (vim.notify (: "mada: unknown subcommand %s" :format
                                      (tostring sub))
                                   vim.log.levels.ERROR)))))))

(log.set_on_error (fn [buf] (M.disable buf)))

M
